# Generated by Django 3.1.5 on 2021-01-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210120_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='pincode',
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
