# Generated by Django 3.1.5 on 2021-01-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210121_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
